####################
# Auto_scatlas_numbat_run_sample.R
# Analysis registry:
# Status: active per-sample compute
# Script: analysis/cnv/Auto_scatlas_numbat_run_sample.R
# Methodology: analysis/methodology/cnv/scatlas_numbat_methodology.md
# Inputs: Auto_scatlas_numbat manifest, count/metadata export, and allele-count file.
# Outputs: per-sample Numbat clone/joint/segment tables and persistent summary RDS.
# Cache/replot: resumes a complete compatible Numbat result when present.
# Run: via analysis/cnv/Auto_run_scatlas_numbat_sample.sh in the Numbat container.
#
# Run Numbat for one scATLAS Carroll/Alcindor sample after allele counts have
# been generated by pileup_and_phase.R. Intended for the official Numbat
# container, mirroring the PDO Numbat run parameters.
####################

suppressPackageStartupMessages({
  library(Matrix)
  library(data.table)
  library(dplyr)
})

out_root <- "/rds/general/project/tumourheterogeneity1/live/scRef_Pipeline/ref_outs/Auto_scatlas_numbat"
local_numbat_lib <- file.path(out_root, "Rlib")
if (dir.exists(local_numbat_lib)) {
  .libPaths(unique(c(local_numbat_lib, .libPaths())))
}

suppressPackageStartupMessages({
  library(numbat)
})

args <- commandArgs(trailingOnly = TRUE)
sample_arg <- if (length(args) >= 1 && nzchar(args[1])) args[1] else Sys.getenv("sample")
manifest_arg <- if (length(args) >= 2 && nzchar(args[2])) args[2] else Sys.getenv("manifest")
ncores <- if (length(args) >= 3 && nzchar(args[3])) as.integer(args[3]) else 12L

if (!nzchar(sample_arg)) stop("Supply sample as first argument or environment variable sample.")
if (!nzchar(manifest_arg)) {
  manifest_arg <- file.path(out_root, "Auto_scatlas_numbat_manifest.csv")
}
if (!file.exists(manifest_arg)) stop("Missing manifest: ", manifest_arg)

manifest <- fread(manifest_arg)
row <- manifest[sample == sample_arg]
if (nrow(row) != 1) stop("Manifest must contain exactly one row for sample: ", sample_arg)

for (path in c(row$count_rds, row$metadata_csv, row$allele_file)) {
  if (!file.exists(path)) stop("Missing Numbat input for ", sample_arg, ": ", path)
}
dir.create(row$numbat_dir, recursive = TRUE, showWarnings = FALSE)

done_file <- file.path(row$numbat_dir, paste0("Auto_", sample_arg, "_numbat_done.txt"))
clone_summary_file <- file.path(row$numbat_dir, paste0("Auto_", sample_arg, "_numbat_clone_post.csv"))
joint_summary_file <- file.path(row$numbat_dir, paste0("Auto_", sample_arg, "_numbat_joint_post.csv.gz"))
map_file <- file.path(row$numbat_dir, paste0("Auto_", sample_arg, "_numbat_cell_map.csv"))

summarise_existing_numbat <- function(status_label, n_cells = NA_integer_, n_genes = NA_integer_, n_allele_rows = NA_integer_, raw_overlap = NA_integer_, prefixed_overlap = NA_integer_) {
  clone_files <- Sys.glob(file.path(row$numbat_dir, "clone_post_*.tsv"))
  if (length(clone_files) == 0) return(FALSE)
  iters <- suppressWarnings(as.integer(sub("^clone_post_([0-9]+)\\.tsv$", "\\1", basename(clone_files))))
  iter_use <- max(iters[is.finite(iters)], na.rm = TRUE)
  if (!is.finite(iter_use)) return(FALSE)
  joint_file <- file.path(row$numbat_dir, paste0("joint_post_", iter_use, ".tsv"))
  segs_file <- file.path(row$numbat_dir, paste0("segs_consensus_", iter_use, ".tsv"))
  if (!file.exists(joint_file) || !file.exists(segs_file)) return(FALSE)

  nb <- Numbat$new(out_dir = row$numbat_dir, i = iter_use, verbose = TRUE)
  clone_post <- as.data.frame(nb$clone_post)
  joint_post <- as.data.frame(nb$joint_post)
  segs_consensus <- as.data.frame(nb$segs_consensus)

  fwrite(clone_post, clone_summary_file)
  fwrite(joint_post, joint_summary_file)
  fwrite(segs_consensus, file.path(row$numbat_dir, paste0("Auto_", sample_arg, "_numbat_segs_consensus.csv")))
  saveRDS(
    list(
      status = status_label,
      sample = sample_arg,
      n_cells = n_cells,
      n_genes = n_genes,
      clone_post = clone_post,
      segs_consensus = segs_consensus,
      numbat_dir = row$numbat_dir
    ),
    file.path(row$numbat_dir, paste0("Auto_", sample_arg, "_numbat_summary.rds"))
  )
  writeLines(
    c(
      paste0("sample\t", sample_arg),
      paste0("status\t", status_label),
      paste0("n_cells\t", n_cells),
      paste0("n_genes\t", n_genes),
      paste0("n_allele_rows\t", n_allele_rows),
      paste0("raw_overlap\t", raw_overlap),
      paste0("prefixed_overlap\t", prefixed_overlap),
      paste0("numbat_iteration\t", iter_use),
      paste0("finished\t", as.character(Sys.time()))
    ),
    done_file
  )
  TRUE
}

####################
write_terminal_no_subclone_status <- function(status_label, n_cells = NA_integer_, n_genes = NA_integer_, n_allele_rows = NA_integer_, raw_overlap = NA_integer_, prefixed_overlap = NA_integer_) {
  status_text <- paste(status_label, collapse = " ")
  clone_post <- data.frame(
    cell = character(),
    clone_opt = character(),
    status = character(),
    stringsAsFactors = FALSE
  )
  joint_post <- data.frame(
    CHROM = character(),
    seg = character(),
    status = character(),
    stringsAsFactors = FALSE
  )
  segs_consensus <- data.frame(
    CHROM = character(),
    start = numeric(),
    end = numeric(),
    status = character(),
    stringsAsFactors = FALSE
  )

  fwrite(clone_post, clone_summary_file)
  fwrite(joint_post, joint_summary_file)
  fwrite(segs_consensus, file.path(row$numbat_dir, paste0("Auto_", sample_arg, "_numbat_segs_consensus.csv")))
  saveRDS(
    list(
      status = status_text,
      sample = sample_arg,
      n_cells = n_cells,
      n_genes = n_genes,
      n_allele_rows = n_allele_rows,
      raw_overlap = raw_overlap,
      prefixed_overlap = prefixed_overlap,
      clone_post = clone_post,
      segs_consensus = segs_consensus,
      numbat_dir = row$numbat_dir,
      terminal_no_subclone = TRUE
    ),
    file.path(row$numbat_dir, paste0("Auto_", sample_arg, "_numbat_summary.rds"))
  )
  writeLines(
    c(
      paste0("sample\t", sample_arg),
      paste0("status\t", status_text),
      paste0("terminal_no_subclone\tTRUE"),
      paste0("n_cells\t", n_cells),
      paste0("n_genes\t", n_genes),
      paste0("n_allele_rows\t", n_allele_rows),
      paste0("raw_overlap\t", raw_overlap),
      paste0("prefixed_overlap\t", prefixed_overlap),
      "numbat_iteration\tNA",
      paste0("finished\t", as.character(Sys.time()))
    ),
    done_file
  )
  TRUE
}
####################

if (file.exists(done_file) && file.exists(clone_summary_file) && file.exists(joint_summary_file)) {
  message("Existing Numbat summary found for ", sample_arg, "; skipping run.")
  quit(save = "no", status = 0)
}
if (file.exists(map_file) && summarise_existing_numbat("Recovered_existing_outputs")) {
  message("Recovered existing Numbat outputs for ", sample_arg)
  quit(save = "no", status = 0)
}

message("Loading raw count matrix: ", row$count_rds)
count_mat <- readRDS(row$count_rds)
if (!inherits(count_mat, "dgCMatrix")) count_mat <- as(count_mat, "dgCMatrix")
count_mat <- count_mat[Matrix::rowSums(count_mat) > 0, Matrix::colSums(count_mat) > 0, drop = FALSE]

message("Loading allele counts: ", row$allele_file)
df_allele <- fread(row$allele_file)
if (!("cell" %in% colnames(df_allele))) stop("Allele count table has no cell column: ", row$allele_file)

raw_cells <- colnames(count_mat)
prefixed_cells <- paste(sample_arg, raw_cells, sep = "_")
allele_cells <- unique(as.character(df_allele$cell))

raw_overlap <- length(intersect(raw_cells, allele_cells))
prefixed_overlap <- length(intersect(prefixed_cells, allele_cells))
if (prefixed_overlap > raw_overlap) {
  colnames(count_mat) <- prefixed_cells
  raw_barcode <- raw_cells
} else {
  raw_barcode <- raw_cells
}

common_cells <- intersect(colnames(count_mat), allele_cells)
if (length(common_cells) < 50) {
  stop("Too few cells shared by counts and allele table for ", sample_arg, ": ", length(common_cells))
}
count_mat <- count_mat[, common_cells, drop = FALSE]
df_allele <- df_allele[cell %in% common_cells]

cell_map <- fread(row$metadata_csv)
cell_map$numbat_cell_raw <- cell_map$raw_barcode
cell_map$numbat_cell_prefixed <- paste(sample_arg, cell_map$raw_barcode, sep = "_")
cell_map$numbat_cell <- if (prefixed_overlap > raw_overlap) {
  cell_map$numbat_cell_prefixed
} else {
  cell_map$numbat_cell_raw
}
cell_map <- cell_map[numbat_cell %in% common_cells]
fwrite(cell_map, map_file)

message("Running Numbat on ", ncol(count_mat), " cells and ", nrow(count_mat), " genes")
status <- tryCatch(
  run_numbat(
    count_mat = count_mat,
    lambdas_ref = ref_hca,
    df_allele = df_allele,
    genome = "hg38",
    out_dir = row$numbat_dir,
    max_iter = 2,
    t = 1e-5,
    gamma = 20,
    init_k = 3,
    min_cells = 50,
    ncores = ncores,
    ncores_nni = ncores,
    call_clonal_loh = TRUE,
    plot = TRUE,
    check_convergence = TRUE,
    verbose = TRUE
  ),
  error = function(e) {
    status_text <- conditionMessage(e)
    message("Numbat returned terminal error/status: ", status_text)
    if (summarise_existing_numbat(status_text, ncol(count_mat), nrow(count_mat), nrow(df_allele), raw_overlap, prefixed_overlap)) {
      message("Recovered complete Numbat outputs despite terminal status for ", sample_arg)
      quit(save = "no", status = 0)
    }
    no_subclone_pattern <- "No clones remain|No CNV remains|No clone remains|No subclone"
    if (grepl(no_subclone_pattern, status_text, ignore.case = TRUE)) {
      write_terminal_no_subclone_status(status_text, ncol(count_mat), nrow(count_mat), nrow(df_allele), raw_overlap, prefixed_overlap)
      message("Marked terminal no-subclone Numbat status for ", sample_arg)
      quit(save = "no", status = 0)
    }
    stop(e)
  }
)

message("Numbat status code: ", status)
if (!summarise_existing_numbat(status, ncol(count_mat), nrow(count_mat), nrow(df_allele), raw_overlap, prefixed_overlap)) {
  write_terminal_no_subclone_status(status, ncol(count_mat), nrow(count_mat), nrow(df_allele), raw_overlap, prefixed_overlap)
  message("Numbat did not write complete clone/joint/segment outputs; marked terminal no-subclone status for ", sample_arg)
}

message("Done: ", sample_arg)
quit(save = "no", status = 0)
